# Generated by Django 4.2.10 on 2024-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_message', models.TextField(max_length=500)),
                ('main_title', models.CharField(max_length=100)),
                ('main_message', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.IntegerField(choices=[(0, 'General Inquiry'), (1, 'Report a Bug'), (2, 'Feature Request'), (3, 'Special Request'), (4, 'Other')], default=0)),
                ('message', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
