# Generated by Django 4.2.10 on 2024-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactaboutsection_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactaboutsection',
            name='hero_message',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='contactaboutsection',
            name='main_message',
            field=models.TextField(max_length=1750),
        ),
    ]
