# Generated by Django 4.2.10 on 2024-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactaboutsection_hero_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
