# Generated by Django 4.2.10 on 2024-02-25 14:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_input_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Code', 'Code')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
