# Generated by Django 4.2.10 on 2024-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_input_type_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_input_type',
        ),
        migrations.AddField(
            model_name='post',
            name='post_code_type',
            field=models.BooleanField(default=False),
        ),
    ]
