# Generated by Django 4.2.10 on 2024-02-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_country_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='main_content_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='location_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='secondary_content',
            field=models.TextField(max_length=1500),
        ),
    ]
