# Generated by Django 4.2.10 on 2024-02-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_country_post_main_content_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
