# Generated by Django 4.2.10 on 2024-02-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_rating_vote_user_vote_remove_post_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Published'), (1, 'Draft')], default=0),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
