# Generated by Django 4.2.10 on 2024-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_country_alter_post_status_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Published'), (1, 'Draft'), (2, 'Flagged')], default=0),
        ),
    ]
